name: mas_ai
description: MAS AI - AI-powered adaptive learning and testing app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.4
  open_filex: ^4.7.0
  shared_preferences: ^2.5.5
  path: ^1.9.1
  file_picker: ^11.0.3
  google_mlkit_text_recognition: ^0.17.1

  syncfusion_flutter_pdf: ^33.2.13
  syncfusion_flutter_pdfviewer: ^33.2.13

  docx_dart: ^1.2.0
  path_provider: ^2.1.5
  pdfx: ^2.11.0
  flutter_quill: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
